language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - pip install nose
  - pip install codecov
script:
  - python -m node --with-coverage
after_success:
  - python -m codecov